sudo: required
services:
  - docker
install: true
stages:
  - test
  - name: push-image
    if: type != pull_request


jobs:
  include:
    - stage: test
      script:
        - ./runTestsDocker.sh
        - ./runTestsCluster.sh skip_build
    - stage: push-image
      if: tag IS present
      script:
      - docker build -t theo .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag theo $DOCKER_IMAGE:$TRAVIS_TAG
      - docker push $DOCKER_IMAGE:$TRAVIS_TAG
      - docker tag theo $DOCKER_IMAGE:latest
      - docker push $DOCKER_IMAGE:latest
