sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
install: true
stages:
  - test
  - build
  - name: push-image
    if: type != pull_request


jobs:
  include:
    - stage: test
      script:
        - docker run --rm -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm i -g npm && npm i --no-optional && npm run build'
        - docker run -d --rm --name theo -e MODE=test -e DATA_PATH=":memory:" -e "ADMIN_TOKEN=testadmin" -e "CLIENT_TOKENS=test1client,test2client" -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm start'
        - docker run --rm --link theo -e "THEO_URL=http://theo:9100" -e "ADMIN_TOKEN=testadmin" -e "CLIENT_TOKENS=test1client,test2client" -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm test'
        - docker stop theo
        - docker run -d --rm --name memcached memcached:1.5-alpine
        - docker run -d --rm --name theo --link memcached -e CACHE_ENABLED=memcached -e "CACHE_URI=memcached:11211" -e MODE=test -e DATA_PATH=":memory:" -e "ADMIN_TOKEN=testadmin" -e "CLIENT_TOKENS=test1client,test2client" -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm start'
        - docker run --rm --link theo -e "THEO_URL=http://theo:9100" -e "ADMIN_TOKEN=testadmin" -e "CLIENT_TOKENS=test1client,test2client" -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm test'
    - stage: build
      script:
        - docker run --rm -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm i -g npm && npm i --no-optional && npm run build'
        - docker build -t theo .
    - stage: push-image
      script:
      - docker run --rm -v $PWD:/usr/local/src -w /usr/local/src node:8-alpine sh -c 'npm i -g npm && npm i --no-optional && npm run build'
      - docker build -t theo .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag theo $DOCKER_IMAGE
      - docker push $DOCKER_IMAGE
