openapi: "3.0.0"
info:
  description: "Theo node - The Authorized Keys Manager. You can find out more about Theo at [https://github.com/theoapp/](https://github.com/theoapp/)."
  version: "0.12.0"
  title: "Theo"
  contact:
    email: "team@authkeys.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /accounts:
    get:
      summary: "Retrieves accounts"
      operationId: listAccount
      parameters:
        - name: "limit"
          in: "query"
          description: "Number of accounts to retrieve"
          required: false
          schema:
            type: "integer"
            format: "int32"
        - name: "offset"
          in: "query"
          description: "Offset of the list"
          required: false
          schema:
            type: "integer"
            format: "int32"
      responses:
        200:
          description: "List of account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountsList"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerTokenAdmin: []
    post:
      summary: "Create new account"
      operationId: addAccount
      security:
        - bearerTokenAdmin: []
      requestBody:
        description: Account to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountNew'
      responses:
        200:
          description: Account response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        400:
          description: "Invalid payload"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidPayloadErrorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /accounts/search:
    get:
      summary: "Search accounts"
      operationId: searchAccount
      parameters:
        - name: "limit"
          in: "query"
          description: "Number of accounts to retrieve"
          required: false
          schema:
            type: "integer"
            format: "int32"
        - name: "offset"
          in: "query"
          description: "Offset of the list"
          required: false
          schema:
            type: "integer"
            format: "int32"
        - name: "name"
          in: "query"
          description: "Search by name"
          required: false
          schema:
            type: "string"
            example: "mac"
        - name: "email"
          in: "query"
          description: "Search by email"
          required: false
          schema:
            type: "string"
            example: "@authkeys.io"
      responses:
        200:
          description: "List of account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountsList"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerTokenAdmin: []
  /accounts/{id}:
    get:
      summary: "Get account"
      operationId: getAccount
      parameters:
        - name: "id"
          in: "path"
          description: "Account ID"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        200:
          description: "Account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        404:
          description: "Account not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerTokenAdmin: []
    put:
      summary: "Edit account"
      operationId: editAccount
      parameters:
        - name: "id"
          in: "path"
          description: "Account ID"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        description: "Fields to edit"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountEdit'
      responses:
        201:
          description: "Done"
        404:
          description: "Account not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerTokenAdmin: []
    delete:
      summary: "Delete account"
      operationId: deleteAccount
      parameters:
        - name: "id"
          in: "path"
          description: "Account ID"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        201:
          description: "Done"
        404:
          description: "Account not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /accounts/{id}/keys:
    post:
      summary: "Add keys to account"
      operationId: addKeysToAccount
      parameters:
        - name: "id"
          in: "path"
          description: "Account ID"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        description: "New key(s) to add"
        required: true
        content:
          application/json:
            schema:
              properties:
                keys:
                  type: "array"
                  items:
                    oneOf:
                      - type: "string"
                        example: "ssh-rsa AAA[...]xv macno@laptop"
                      - $ref: "#/components/schemas/PublicKeyNew"
      responses:
        200:
          description: Account response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        400:
          description: "Invalid payload"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidPayloadErrorResponse'
        404:
          description: "Account not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerTokenAdmin:
      type: http
      scheme: bearer
    bearerTokenAgent:
      type: http
      scheme: bearer
  schemas:
    BasicList:
      type: "object"
      required:
        - "total"
        - "limit"
        - "offset"
        - "rows"
      properties:
        total:
          type: "integer"
          format: "int32"
        limit:
          type: "integer"
          format: "int32"
        offset:
          type: "integer"
          format: "int32"
        rows:
          type: "array"
          items:
            type: "string"
    AccountNew:
      type: "object"
      required:
        - "name"
        - "email"
      properties:
        name:
          type: "string"
          example: "Michele"
        email:
          type: "string"
          example: "macno@authkeys.io"
        expire_at:
          type: "integer"
          format: "int64"
          nullable: true
        keys:
          type: "array"
          items:
            oneOf:
              - type: "string"
                example: "ssh-rsa AAA[...]xv macno@laptop"
              - $ref: "#/components/schemas/PublicKeyNew"
    AccountEdit:
      type: "object"
      properties:
        expire_at:
          type: "integer"
          format: "int64"
          nullable: true
        active:
          $ref: "#/components/schemas/Active"
    AccountMinimal:
      type: "object"
      required:
        - "id"
        - "name"
        - "email"
        - "active"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
          example: "Michele"
        email:
          type: "string"
          example: "macno@authkeys.io"
        active:
          $ref: "#/components/schemas/Active"
    Account:
      allOf:
        - $ref: '#/components/schemas/AccountMinimal'
        - type: "object"
          required:
            - "expire_at"
            - "public_keys"
            - "groups"
            - "permissions"
          properties:
            expire_at:
              type: "integer"
              format: "int64"
              example: 0
            public_keys:
              type: "array"
              items:
                $ref: '#/components/schemas/PublicKey'
            groups:
              type: "array"
              items:
                $ref: '#/components/schemas/Group'
            permissions:
              items:
                $ref: '#/components/schemas/Permission'
    AccountsList:
      allOf:
        - $ref: '#/components/schemas/BasicList'
        - type: "object"
          properties:
            rows:
              type: "array"
              items:
                $ref: "#/components/schemas/AccountMinimal"
    PublicKeyNew:
      type: "object"
      required:
        - "key"
      properties:
        key:
          type: "string"
          example: "ssh-rsa AAA[...]xv macno@laptop"
        signature:
          type: "string"
          example: "XgRI6y3[...]S0ZFHN"
          nullable: true
    PublicKey:
      type: "object"
      required:
        - "id"
        - "public_key"
        - "public_key_sig"
        - "created_at"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 213
        public_key:
          type: "string"
          example: "ssh-rsa AAA[...]xv macno@laptop"
        public_key_sig:
          type: "string"
          example: "XgRI6y3[...]S0ZFHN"
          nullable: true
        created_at:
          type: "integer"
          format: "int64"
          example: 1539688358693
    Active:
      type: "integer"
      format: "int32"
      minimum: 0
      maximum: 1
    AccountResponse:
      type: "object"
      required:
        - "account_id"
        - "public_keys"
      properties:
        account_id:
          type: "integer"
          format: "int32"
          example: 146
        public_keys:
          type: "array"
          items:
            $ref: "#/components/schemas/PublicKey"
    Group:
      type: "object"
      required:
        - "id"
        - "name"
        - "active"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1234
        name:
          type: "string"
          example: "developers"
        active:
          $ref: "#/components/schemas/Active"
    Permission:
      type: "object"
      required:
        - "id"
        - "user"
        - "host"
        - "created_at"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1234
        user:
          type: "string"
          example: "root"
        host:
          type: "string"
          example: "server1"
        created_at:
          type: "integer"
          format: "int64"
          example: 1539688358693
    ErrorResponse:
      type: "object"
      required:
        - "status"
        - "reason"
      properties:
        status:
          type: "integer"
          format: "int32"
          example: 500
        reason:
          type: "string"
          example: "Internal Server Error"
    NotFoundErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: "object"
          properties:
            status:
              example: 404
            reason:
              example: "Item not found"
    InvalidPayloadErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: "object"
          properties:
            status:
              example: 400
            reason:
              example: "Invalid payload"
externalDocs:
  description: "Find out more about Theo"
  url: "https://github.com/theoapp/"
